### ISSUE TITLE
Fibers dependency breaks in node 16

### ISSUE THREAD

**Issue by MexHigh** [flareact/flareact#153]
### Describe the problem:

With node v.16.0.0 and while executing `npm run dev` or `npm run build`, the following error occurs:

```
[worker] ## There is an issue with `node-fibers` ##
[worker] `/home/leon/Code/shared-music-db/node_modules/fibers/bin/linux-x64-93-glibc/fibers.node` is missing.
[worker] 
[worker] Try running this to fix the issue: /home/leon/.nvm/versions/node/v16.0.0/bin/node /home/leon/Code/shared-music-db/node_modules/fibers/build
[worker] Error: Cannot find module '/home/leon/Code/shared-music-db/node_modules/fibers/bin/linux-x64-93-glibc/fibers'
[worker] Require stack:
[worker] - /home/leon/Code/shared-music-db/node_modules/fibers/fibers.js
[worker] - /home/leon/Code/shared-music-db/node_modules/flareact/configs/webpack.config.js
[worker] - /home/leon/Code/shared-music-db/node_modules/flareact/configs/webpack.worker.config.js
[worker] - /home/leon/Code/shared-music-db/node_modules/flareact/webpack.js
[worker] - /home/leon/.cache/.wrangler/wranglerjs-1.15.0/index.js
[worker]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
[worker]     at Function.Module._load (node:internal/modules/cjs/loader:773:27)
[worker]     at Module.require (node:internal/modules/cjs/loader:1012:19)
[worker]     at require (node:internal/modules/cjs/helpers:93:18)
[worker]     at Object.<anonymous> (/home/leon/Code/shared-music-db/node_modules/fibers/fibers.js:14:39)
[worker]     at Module._compile (node:internal/modules/cjs/loader:1108:14)
[worker]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
[worker]     at Module.load (node:internal/modules/cjs/loader:988:32)
[worker]     at Function.Module._load (node:internal/modules/cjs/loader:828:14)
[worker]     at Module.require (node:internal/modules/cjs/loader:1012:19)
[worker]     at require (node:internal/modules/cjs/helpers:93:18)
[worker]     at module.exports (/home/leon/Code/shared-music-db/node_modules/flareact/configs/webpack.config.js:29:16)
[worker]     at module.exports (/home/leon/Code/shared-music-db/node_modules/flareact/configs/webpack.worker.config.js:26:8)
[worker]     at /home/leon/.cache/.wrangler/wranglerjs-1.15.0/index.js:43:50
[worker]     at Object.<anonymous> (/home/leon/.cache/.wrangler/wranglerjs-1.15.0/index.js:139:3)
[worker]     at Module._compile (node:internal/modules/cjs/loader:1108:14)
[worker] /home/leon/Code/shared-music-db/node_modules/fibers/fibers.js:23
[worker]                throw new Error('Missing binary. See message above.');
[worker]                      ^
[worker] 
[worker] Error: Missing binary. See message above.
[worker]     at Object.<anonymous> (/home/leon/Code/shared-music-db/node_modules/fibers/fibers.js:23:9)
[worker]     at Module._compile (node:internal/modules/cjs/loader:1108:14)
[worker]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
[worker]     at Module.load (node:internal/modules/cjs/loader:988:32)
[worker]     at Function.Module._load (node:internal/modules/cjs/loader:828:14)
[worker]     at Module.require (node:internal/modules/cjs/loader:1012:19)
[worker]     at require (node:internal/modules/cjs/helpers:93:18)
[worker]     at module.exports (/home/leon/Code/shared-music-db/node_modules/flareact/configs/webpack.config.js:29:16)
[worker]     at module.exports (/home/leon/Code/shared-music-db/node_modules/flareact/configs/webpack.worker.config.js:26:8)
[worker]     at /home/leon/.cache/.wrangler/wranglerjs-1.15.0/index.js:43:50
[worker]     at Object.<anonymous> (/home/leon/.cache/.wrangler/wranglerjs-1.15.0/index.js:139:3)
[worker]     at Module._compile (node:internal/modules/cjs/loader:1108:14)
[worker]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
[worker]     at Module.load (node:internal/modules/cjs/loader:988:32)
[worker]     at Function.Module._load (node:internal/modules/cjs/loader:828:14)
[worker]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
[worker] Error: failed to execute `"/home/leon/.nvm/versions/node/v16.0.0/bin/node" "/home/leon/.cache/.wrangler/wranglerjs-1.15.0" "--output-file=/tmp/.wranglerjs_outputx5SQc" "--wasm-binding=WASM_MODULE" "--webpack-config=node_modules/flareact/webpack"`: exited with exit code: 1
[worker] wrangler dev exited with code 1
--> Sending SIGTERM to other processes..
[client] ## There is an issue with `node-fibers` ##
[client] `/home/leon/Code/shared-music-db/node_modules/fibers/bin/linux-x64-93-glibc/fibers.node` is missing.
[client] 
[client] Try running this to fix the issue: /home/leon/.nvm/versions/node/v16.0.0/bin/node /home/leon/Code/shared-music-db/node_modules/fibers/build
[client] Error: Cannot find module '/home/leon/Code/shared-music-db/node_modules/fibers/bin/linux-x64-93-glibc/fibers'
[client] Require stack:
[client] - /home/leon/Code/shared-music-db/node_modules/fibers/fibers.js
[client] - /home/leon/Code/shared-music-db/node_modules/flareact/configs/webpack.config.js
[client] - /home/leon/Code/shared-music-db/node_modules/flareact/configs/webpack.client.config.js
[client] - /home/leon/Code/shared-music-db/node_modules/webpack-cli/bin/utils/convert-argv.js
[client] - /home/leon/Code/shared-music-db/node_modules/webpack-dev-server/bin/webpack-dev-server.js
[client]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
[client]     at Function.Module._load (node:internal/modules/cjs/loader:773:27)
[client]     at Module.require (node:internal/modules/cjs/loader:1012:19)
[client]     at require (node:internal/modules/cjs/helpers:93:18)
[client]     at Object.<anonymous> (/home/leon/Code/shared-music-db/node_modules/fibers/fibers.js:14:39)
[client]     at Module._compile (node:internal/modules/cjs/loader:1108:14)
[client]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
[client]     at Module.load (node:internal/modules/cjs/loader:988:32)
[client]     at Function.Module._load (node:internal/modules/cjs/loader:828:14)
[client]     at Module.require (node:internal/modules/cjs/loader:1012:19)
[client] /home/leon/Code/shared-music-db/node_modules/fibers/fibers.js:23
[client]                throw new Error('Missing binary. See message above.');
[client]                ^
[client] 
[client] Error: Missing binary. See message above.
[client]     at Object.<anonymous> (/home/leon/Code/shared-music-db/node_modules/fibers/fibers.js:23:9)
[client]     at Module._compile (node:internal/modules/cjs/loader:1108:14)
[client]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
[client]     at Module.load (node:internal/modules/cjs/loader:988:32)
[client]     at Function.Module._load (node:internal/modules/cjs/loader:828:14)
[client]     at Module.require (node:internal/modules/cjs/loader:1012:19)
[client]     at require (node:internal/modules/cjs/helpers:93:18)
[client]     at module.exports (/home/leon/Code/shared-music-db/node_modules/flareact/configs/webpack.config.js:29:16)
[client]     at module.exports (/home/leon/Code/shared-music-db/node_modules/flareact/configs/webpack.client.config.js:86:8)
[client]     at handleFunction (/home/leon/Code/shared-music-db/node_modules/webpack-cli/bin/utils/prepareOptions.js:21:13)
[client] webpack-dev-server --config node_modules/flareact/configs/webpack.client.config.js --mode development exited with code 1
[
  {
    command: {
      command: 'wrangler dev',
      name: 'worker',
      prefixColor: '',
      env: [Object]
    },
    index: 0,
    exitCode: 1
  },
  {
    command: {
      command: 'webpack-dev-server --config node_modules/flareact/configs/webpack.client.config.js --mode development',
      name: 'client',
      prefixColor: '',
      env: [Object]
    },
    index: 1,
    exitCode: 1
  }
]
```

Executing `/home/leon/.nvm/versions/node/v16.0.0/bin/node /home/leon/Code/shared-music-db/node_modules/fibers/build` as opposed results in an `node-gyp` error code 1 and the hint to use a supported platform and node version.

When switching to node v.15.14.0 (via `nvm use 15`), everything works fine. This happens with two of my own flareact projects.

### Link to a minimal reproduction:

Just take any Flareact Repo and execute `npm i` and `npm run dev` when using node v16.0.0.

**EDIT:** It seems like `node-fibers` actually stopped working as of April 13th, 2021 as mentioned in the README.md of https://github.com/laverdet/node-fibers. It does not seems like that the project will be maintained any longer.

**Comment by tj-kev** [comment]
Looks like the fibers package has no plans to provide v16 compatibility. There is a note on the repo here: https://github.com/laverdet/node-fibers

Its used in the webpack config here:
https://github.com/flareact/flareact/blob/6544f5d3e6bc102946b2d2dc7f7fecb319ac2922/configs/webpack.config.js#L29

It could removed, although this would slow the compilation time, as described here:
https://webpack.js.org/loaders/sass-loader/#implementation

**Comment by konsumer** [comment]
Maybe another angle is this: I really like vite. It's incredibly fast, and versatile, and so easy to use. It uses rollup, and does builds & HMR faster, with very little config needed (none, by default), with pretty rad frontend-support (for example vue, preact, react, full postcss, less, sass, stylus, etc.)

if I could separate flareact's server, react-stuff & build from webpack, it seems like it might be fairly straightforward to integrate with vite. They talk about SSR a bit [here](https://vitejs.dev/guide/ssr.html). Looks like they have ready-made express-style middleware, and can do a lot of the work, and not even need a proxy for local dev. Maybe it would make sense to separate stuff into a core react-only project, and a "frontend SSR tools" project, and then I could make a flarevue, for example (or maybe just a single flare thing, that is essentially a vite-wrapper, that supports react & vue and more, via vite.)

They also have "community-templates" for starting a project, so maybe I could just make a `cloudflare-react` template for that, too.

I am thinking to make it, I would need this:

- router (probly just copied)
- components like `Link`  (probly just copied)
- worker stuff for deploy  (probly just mostly copied)
- dev-server entry-point for vite (not sure about this part)

What do you think?

**Comment by konsumer** [comment]
I looked around a bit, and found [this](https://vitedge.js.org/), which I think might do what I want to do. It's not exactly like nextjs, but seems to have all the stuff.

**Comment by leonidlewis** [comment]
I am building some project using Nuxt.js and deploy at the netlify but have  encountered such problem. Where can I add the fiber: require("fibers") in the Nuxt.js project. In the nuxt.config.js?

**Comment by mikecann** [comment]
any movement on this, its a bit of a gotcha if you are trying to build using node 16

**Comment by tj-kev** [comment]
Sorry, not had time to look into it yet. 

It does need removing if the package is no longer maintained but need to see the impact on performance and if alternatives would be required.
