### ISSUE TITLE
Cannot install flareact on Manjaro

### ISSUE THREAD

**Issue by ContrapunctusII** [flareact/flareact#261]
### Describe the problem:

I encounter this issue everytime I run `npm install flareact` on Manjaro with kernel 6.6.46-1-MANJARO.

```
5737 info run fibers@5.0.3 install node_modules/fibers node build.js || nodejs build.js
5738 info run fibers@5.0.3 install { code: 127, signal: null }
5739 verbose stack Error: command failed
5739 verbose stack     at promiseSpawn (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
5739 verbose stack     at spawnWithShell (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:124:10)
5739 verbose stack     at promiseSpawn (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:12:12)
5739 verbose stack     at runScriptPkg (/usr/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:77:13)
5739 verbose stack     at runScript (/usr/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:12)
5739 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/rebuild.js:329:17
5739 verbose stack     at run (/usr/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:67:22)
5739 verbose stack     at /usr/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:84:9
5739 verbose stack     at new Promise (<anonymous>)
5739 verbose stack     at callLimit (/usr/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:35:69)
5740 verbose pkgid fibers@5.0.3
5741 error code 127
5742 error path /home/user/Code/proxy-express/node_modules/fibers
5743 error command failed
5744 error command sh -c node build.js || nodejs build.js
5745 error make : on entre dans le répertoire « /home/user/Code/proxy-express/node_modules/fibers/build »
5745 error   CXX(target) Release/obj.target/fibers/src/fibers.o
5745 error make : on quitte le répertoire « /home/user/Code/proxy-express/node_modules/fibers/build »
5746 error gyp info it worked if it ends with ok
5746 error gyp info using node-gyp@10.1.0
5746 error gyp info using node@22.6.0 | linux | x64
5746 error gyp info find Python using Python version 3.12.4 found at "/usr/bin/python3"
5746 error gyp info spawn /usr/bin/python3
5746 error gyp info spawn args [
5746 error gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
5746 error gyp info spawn args 'binding.gyp',
5746 error gyp info spawn args '-f',
5746 error gyp info spawn args 'make',
5746 error gyp info spawn args '-I',
5746 error gyp info spawn args '/home/user/Code/proxy-express/node_modules/fibers/build/config.gypi',
5746 error gyp info spawn args '-I',
5746 error gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
5746 error gyp info spawn args '-I',
5746 error gyp info spawn args '/home/user/.cache/node-gyp/22.6.0/include/node/common.gypi',
5746 error gyp info spawn args '-Dlibrary=shared_library',
5746 error gyp info spawn args '-Dvisibility=default',
5746 error gyp info spawn args '-Dnode_root_dir=/home/user/.cache/node-gyp/22.6.0',
5746 error gyp info spawn args '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
5746 error gyp info spawn args '-Dnode_lib_file=/home/user/.cache/node-gyp/22.6.0/<(target_arch)/node.lib',
5746 error gyp info spawn args '-Dmodule_root_dir=/home/user/Code/proxy-express/node_modules/fibers',
5746 error gyp info spawn args '-Dnode_engine=v8',
5746 error gyp info spawn args '--depth=.',
5746 error gyp info spawn args '--no-parallel',
5746 error gyp info spawn args '--generator-output',
5746 error gyp info spawn args 'build',
5746 error gyp info spawn args '-Goutput_dir=.'
5746 error gyp info spawn args ]
5746 error gyp info spawn make
5746 error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
5746 error ../src/fibers.cc: Dans la fonction « void uni::MakeWeak(v8::Isolate*, v8::Persistent<T>&, P*) »:
5746 error ../src/fibers.cc:27:79: erreur: « kFinalizer » n'est pas un membre de « v8::WeakCallbackType »
5746 error    27 |                 handle.SetWeak(val, WeakCallbackShim<F, P>, WeakCallbackType::kFinalizer);
5746 error       |                                                                               ^~~~~~~~~~
5746 error ../src/fibers.cc: Dans la fonction « void uni::SetAccessor(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, FunctionType (*)(v8::Local<v8::String>, const GetterCallbackInfo&), void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const SetterCallbackInfo&)) »:
5746 error ../src/fibers.cc:355:73: attention: transtypage entre types de fonctions incompatibles de « uni::FunctionType (*)(v8::Local<v8::String>, const uni::GetterCallbackInfo&) » {aka « void (*)(v8::Local<v8::String>, const v8::PropertyCallbackInfo<v8::Value>&) »} vers « v8::AccessorNameGetterCallback » {aka « void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&) »} [-Wcast-function-type]
5746 error   355 |                 object->SetAccessor(isolate->GetCurrentContext(), name, (AccessorNameGetterCallback)getter, (AccessorNameSetterCallback)setter).ToChecked();
5746 error       |                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
5746 error ../src/fibers.cc:355:109: attention: transtypage entre types de fonctions incompatibles de « void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const uni::SetterCallbackInfo&) » {aka « void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&) »} vers « v8::AccessorNameSetterCallback » {aka « void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&) »} [-Wcast-function-type]
5746 error   355 |                 object->SetAccessor(isolate->GetCurrentContext(), name, (AccessorNameGetterCallback)getter, (AccessorNameSetterCallback)setter).ToChecked();
5746 error       |                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
5746 error Dans le fichier inclus depuis ../src/coroutine.h:1,
5746 error                  depuis ../src/fibers.cc:1:
5746 error ../src/fibers.cc: Au niveau global:
5746 error /home/user/.cache/node-gyp/22.6.0/include/node/node.h:1232:7: attention: transtypage entre types de fonctions incompatibles de « void (*)(v8::Local<v8::Object>) » vers « node::addon_register_func » {aka « void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*) »} [-Wcast-function-type]
5746 error  1232 |       (node::addon_register_func) (regfunc),                          \
5746 error       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
5746 error /home/user/.cache/node-gyp/22.6.0/include/node/node.h:1266:3: note: dans l'expansion de la macro « NODE_MODULE_X »
5746 error  1266 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
5746 error       |   ^~~~~~~~~~~~~
5746 error ../src/fibers.cc:930:1: note: dans l'expansion de la macro « NODE_MODULE »
5746 error   930 | NODE_MODULE(fibers, init)
5746 error       | ^~~~~~~~~~~
5746 error make: *** [fibers.target.mk:116: Release/obj.target/fibers/src/fibers.o] Error 1
5746 error gyp ERR! build error 
5746 error gyp ERR! stack Error: `make` failed with exit code: 2
5746 error gyp ERR! stack at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
5746 error gyp ERR! System Linux 6.6.46-1-MANJARO
5746 error gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
5746 error gyp ERR! cwd /home/user/Code/proxy-express/node_modules/fibers
5746 error gyp ERR! node -v v22.6.0
5746 error gyp ERR! node-gyp -v v10.1.0
5746 error gyp ERR! not ok 
5746 error node-gyp exited with code: 1
5746 error Please make sure you are using a supported platform and node version. If you
5746 error would like to compile fibers on this machine please make sure you have setup your
5746 error build environment--
5746 error Windows + OS X instructions here: https://github.com/nodejs/node-gyp
5746 error Ubuntu users please run: `sudo apt-get install g++ build-essential`
5746 error RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
5746 error Alpine users please run: `sudo apk add python make g++`
5746 error sh: ligne 1: nodejs : commande introuvable
```

### Link to a minimal reproduction:

Just try to install Flareact on Manjaro.

**Comment by ContrapunctusII** [comment]
Had it working with Node 16.
