### ISSUE TITLE
Flareact dev Error 522

### ISSUE THREAD

**Issue by insuusvenerati** [flareact/flareact#28]
Getting an error in the browser from Cloudflare when running `flareact dev` in a new project.

Error looks like this https://i.imgur.com/0UvmX4K.png

Flareact at `0.6.0-canary.2`

Potentially relevant information:

- Running latest windows 10 pro.
- NodeJS v14.9.0
- Cloudflare namespace is completely empty. `out` directory is empty.
- If you run `flareact build` first then `flareact dev` the namespace is populated with the `_flareact` directory and it's contents but the error still persists.

Console errors:
```
> flareact dev

Starting Flareact dev server...
[client] [BABEL] Note: The code generator has deoptimised the styling of D:\Code\JS\Flareact\flareact-notes\node_modules\react-dom\cjs\react-dom.development.js as it exceeds the max of 500KB.
[worker]  Built successfully, built project size is 34 KiB.
[worker]  Created namespace for Workers Site "__flareact-notes-workers_sites_assets_preview"
[worker]  Success
[worker]  Listening on http://127.0.0.1:8787
[worker]  Detected changes...
[worker]  Ignoring stale first change
[worker] Uncaught
[worker] TypeError: Cannot set property 'wrap' of undefined
[worker]     at worker.js:6:24464
[worker]     at Module.<anonymous> (worker.js:6:29577)
[worker]     at Module.<anonymous> (worker.js:6:29688)
[worker]     at n (worker.js:1:110)
[worker]     at Object.<anonymous> (worker.js:1:1299)
[worker]     at n (worker.js:1:110)
[worker]     at Module.<anonymous> (worker.js:6:97960)
[worker]     at n (worker.js:1:110)
[worker]     at worker.js:1:902
[worker]     at worker.js:1:912
```

**Comment by insuusvenerati** [comment]
@jplhomer saw you wanted me to try flareact@canary so I went ahead and tried it. Same errors as before besides the ones that got fixed in the PR

**Comment by wizzard0** [comment]
Reproduces exactly as described on `v1.1.0`. Win10 v20H2, node v12

**Comment by wizzard0** [comment]
Possibly helpful workaround for those who decide to run flareact under WSL: install node with `nvs` or `nvm`, not via website instructions, otherwise `npm i @cloudflare/wrangler` will fail %)
