### ISSUE TITLE
Unable to deploy, with error on minified css

### ISSUE THREAD

**Issue by nogamenofun98** [flareact/flareact#97]
```
[publish]
[publish] ERROR in ./node_modules/@fortawesome/fontawesome-free/css/all.min.css
[publish] Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
[publish] ModuleParseError: Module parse failed: Unexpected character '' (1:4)
[publish] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
[publish] (Source code omitted for this binary file)
[publish]     at handleParseError (D:\WebstormProjects\customer-frontend-flareact\node_modules\webpack\lib\NormalModule.js:469:19)
[publish]     at D:\WebstormProjects\customer-frontend-flareact\node_modules\webpack\lib\NormalModule.js:503:5
[publish]     at D:\WebstormProjects\customer-frontend-flareact\node_modules\webpack\lib\NormalModule.js:358:12
[publish]     at D:\WebstormProjects\customer-frontend-flareact\node_modules\loader-runner\lib\LoaderRunner.js:373:3
[publish]     at iterateNormalLoaders (D:\WebstormProjects\customer-frontend-flareact\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
[publish]     at Array.<anonymous> (D:\WebstormProjects\customer-frontend-flareact\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
[publish]     at Storage.finished (D:\WebstormProjects\customer-frontend-flareact\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
[publish]     at D:\WebstormProjects\customer-frontend-flareact\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
[publish]     at D:\WebstormProjects\customer-frontend-flareact\node_modules\graceful-fs\graceful-fs.js:123:16
[publish]     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
[publish] webpack --config node_modules/flareact/configs/webpack.client.config.js --out ./out --mode production && wrangler publish exited with code 2
[
  {
    command: {
      command: 'webpack --config node_modules/flareact/configs/webpack.client.config.js --out ./out --mode production && wrangler publish',
      name: 'publish',
      prefixColor: '',
      env: [Object]
    },
    index: 0,
    exitCode: 2
  }
]
```

i installed postcss and postcss-loader, but it still failed to deploy.

Below is my flareact.config.js
```
module.exports = {
	webpack: (config, options) => {
		config.module.rules.push(
			{
				test: /\.(svg)$/,
				use: [
					{ loader: "file-loader", options: {} },
					{ loader: "svg-url-loader", options: {} },
				],
			},
			{
				test: /\.(ttf|eot|png|jpg|gif|ico)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
				use: [
					{ loader: "file-loader", options: {} },
					{
						loader: "url-loader",
						options: {
							limit: 10000,
						},
					},
				],
			}
		);
		config.node = {
			fs: "empty",
		};

		return config;
	},
};

```

**Comment by jplhomer** [comment]
Hi! Unfortunately I can't help unless you provide the code related to the error above. It looks like you're importing a CSS file from `node_modules`, but it's not clear where or how that's happening. Feel free to re-open if you are able to provide that.
